naver-cloud-sms:
accessKey: "XsaKYAismYxbkeJwXlx5b8j0S1nmPjoMkSfxzrSH? TP8lL2kLNHFYQHcttK9G"
secretKey: "XsaKYAismYxbkeJwXlx5b8j0S1nmPjoMkSfxzrSH"
serviceId: "ncp:sms:kr:336007695122:sns"
senderPhone: "01074199611"

spring.redis:
host: "localhost"
port: "6379"

naver-ai-geocoder:
clientId: "ehdjldyrx2"
clientSecret: "mUi7qxLn2o7zIup9lC0wUJhr5rIOFAC068DCoF26"